Check if xdpyinfo is installed

diff --git a/.local/bin/recorder b/.local/bin/recorder
--- a/.local/bin/recorder
+++ b/.local/bin/recorder
@@ -26,28 +26,42 @@ lookahead="8"
 bframes="4"
 cq="19"
 
+#  -----------
+# | Functions |
+#  -----------
+
+function record() {
+	cd $directory
+	ffmpeg -loglevel $loglevel \
+		-video_size $size \
+		-f $method \
+		-i :0.0+1920,0 \
+		-hwaccel $hwaccel \
+		-hwaccel_output_format $hwaccel \
+		-f $audio \
+		-i $sink \
+		-preset $preset \
+		-profile:v $profile \
+		-tune $tune \
+		-rc-lookahead $lookahead \
+		-bf $bframes \
+		-rc $rc \
+		-cq $cq \
+		-b:v $bitrate \
+		-maxrate $maxrate \
+		-bufsize $buffer \
+		-c:v \
+		$video $name.$ext
+}
+
 #  ------
 # | Main |
 #  ------
 
-cd $directory
-ffmpeg -loglevel $loglevel \
-	-video_size $size \
-	-f $method \
-	-i :0.0+1920,0 \
-	-hwaccel $hwaccel \
-	-hwaccel_output_format $hwaccel \
-	-f $audio \
-	-i $sink \
-	-preset $preset \
-	-profile:v $profile \
-	-tune $tune \
-	-rc-lookahead $lookahead \
-	-bf $bframes \
-	-rc $rc \
-	-cq $cq \
-	-b:v $bitrate \
-	-maxrate $maxrate \
-	-bufsize $buffer \
-	-c:v \
-	$video $name.$ext
+if ! command -v xdpyinfo &> /dev/null
+then
+	printf "xdpyinfo not found\n"
+	exit 1
+else
+	record
+fi
